arb-dir: lib/l10n                                 # The directory where the translation files are stored
template-arb-file: app_en.arb                     # A template file where string parameters are described
output-localization-file: app_localizations.dart # Generated localization file
#nullable-getter: false                            # The rows can be accessed via the no-nullable method of(context)